FROM node:12-alpine as build

WORKDIR /usr/local/bottwo

COPY bot/dist/bot2 bot/package.json bot/.env ./

RUN npm install --production

FROM node:12-alpine

WORKDIR /usr/local/bottwo

COPY --from=build /usr/local/bottwo .

CMD ["node", "index.js"]