FROM node:12-alpine as build

WORKDIR /usr/local/botfour

COPY dist/bot4 package.json .env ./

RUN npm install --production

FROM node:12-alpine

WORKDIR /usr/local/botfour

COPY --from=build /usr/local/botfour .

CMD ["node", "index.js"]